#!/usr/bin/python2.7

import telebot
import os
import time
import requests
import logging
import configparser

config = configparser.ConfigParser()
config.readfp(open(r'/usr/etc/not_tob.cfg'))
token = config.get('bot', 'token')
logging.info(token)
chatid = config.get('bot', 'chatid')
logging.info(chatid)
hostname = os.uname()[1]

print ("Not_toB is runnint and checking WHO. Token : %s / Chat_id : %s."%(token,chatid))

bot = telebot.TeleBot(token)
bot.send_message(chatid,"I'm running and checking WHO on %s" %hostname)

def diff(list1, list2):
    c = set(list1).union(set(list2))
    d = set(list1).intersection(set(list2))
    return list(c - d)

t=1
presockstat = ['']
while t==1 :
        sockstat = os.popen('who').read()
        sockstat = sockstat.split('\n')
        #temp3 = [item for item in sockstat if item not in presockstat]
        #print (temp3)
        if (sockstat != presockstat) and (sockstat != ''):
                difflist = diff(sockstat, presockstat)
                if (len(sockstat) > len(presockstat)):
                        if 'root' in ''.join(difflist):
                                bot.send_message(chatid,'!!!ROOT LOGIN  DETECTED!!!')
                                logging.warning("The root has logged in.".join(difflist))                                                                                                             
                        bot.send_message(chatid,'IN@%s: %s'%(hostname,''.join(difflist)))                                                                                                              
                if (len(sockstat) < len(presockstat)):
                        bot.send_message(chatid,'OUT@%s: %s'%(hostname,''.join(difflist)))                                                                                                          
        if (sockstat != presockstat) and (sockstat == ''):
                bot.send_message('@%s There is no users'%(hostname))
        presockstat = sockstat
        time.sleep(10)
